routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\InfoWebController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Livewire\Admin\Article\ArticleCreate;
use App\Http\Livewire\Admin\Article\ArticleEdit;
use App\Http\Livewire\Admin\Article\ArticleIndex;
use App\Http\Livewire\Admin\Category\CategoryCreate;
use App\Http\Livewire\Admin\Category\CategoryEdit;
use App\Http\Livewire\Admin\Category\CategoryIndex;
use App\Http\Livewire\Admin\Code\CodeIndex;
use App\Http\Livewire\Admin\File\FileIndex;
use App\Http\Livewire\Admin\Product\ProductCreate;
use App\Http\Livewire\Admin\Product\ProductEdit;
use App\Http\Livewire\Admin\Product\ProductIndex;
use App\Http\Livewire\Admin\Slide\LogoIndex;
use App\Http\Livewire\Admin\Slide\SlideCreate;
use App\Http\Livewire\Admin\Slide\SlideEdit;
use App\Http\Livewire\Admin\Slide\SlideIndex;
use App\Http\Livewire\Admin\WebInfo\WebInfoIndex;
use App\Models\WebInformation;
use Illuminate\Support\Facades\Route;



// Main route admin
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified', 'locale', 'is_admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [BaseController::class, 'dashboard'])->name('admin.dashboard');
        // Route::resource('/product', ProductController::class);
        // Route::resource('/article', ArticleController::class);
        // Route::resource('/category',CategoryController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/channel', ChannelController::class);
        Route::resource('/partner', PartnerController::class);
        Route::resource('/order', OrderController::class);
        Route::resource('/infoweb', InfoWebController::class);
        Route::get('/info', [InformationController::class, 'show'])->name('info.show');
        Route::put('/info', [InformationController::class, 'save'])->name('info.save');
        Route::put('/update-password', [UserController::class, 'updatePassword'])->name('users.update-password');
        Route::get('change-language/{lang}', [BaseController::class, 'changeLanguage'])->name('admin.changeLanguage');
        Route::get('channel/{channelSlug}', [BaseController::class, 'channel'])->name('admin.channel');
        Route::get('posts/api', [PostController::class, 'getPosts']);

        //logo
        Route::get('web-info', WebInfoIndex::class)->name('webinfo.index');
        // Route::post('/',[LogoController::class,'changeLogoImage'])->name('change.logo');
        //File
        Route::get('file', FileIndex::class)->name('file.index');
        // Slide
        Route::get('slide',SlideIndex::class)->name('slide.index');
        Route::get('slide/create',SlideCreate::class)->name('slide.create');
        Route::get('slide/edit/{slide}',SlideEdit::class)->name('slide.edit');
        // Code 
        // Route::get('code',CodeIndex::class)->name('code.index');
        //Category 
        Route::get('category', CategoryIndex::class)->name('category.index');
        Route::get('category/create', CategoryCreate::class)->name('category.create');
        Route::get('category/edit/{category}', CategoryEdit::class)->name('category.edit');
        // Product
        Route::get('product', ProductIndex::class)->name('product.index');
        Route::get('product/create', ProductCreate::class)->name('product.create');
        Route::get('product/edit/{product}', ProductEdit::class)->name('product.edit');
        // Article
        Route::get('article', ArticleIndex::class)->name('article.index');
        Route::get('article/create', ArticleCreate::class)->name('article.create');
        Route::get('article/edit/{article}', ArticleEdit::class)->name('article.edit');
    });
});

//Jetstream livewire
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

routes/web.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.layouts.index');
// });

// Route::middleware(['locale'])->group(function(){
    Route::prefix('/')->group(function(){
        Route::get('',[HomeController::class, 'index'])->name('index');
        Route::get('detail/{slug}',[HomeController::class, 'productDetail'])->name('product.detail');
        Route::get('cate/{slug}',[HomeController::class, 'category'])->name('category.product.list');
        Route::get('article',[HomeController::class,'article']);
        Route::get('article/{slug}',[HomeController::class, 'articleDetail'])->name('article.detail');
        Route::get('contact',[HomeController::class, 'contact'])->name('contact');
        Route::get('storeContact',[HomeController::class,'storeContact'])->name('storeContact');
        Route::post('search',[HomeController::class, 'search'])->name('search');
        Route::get('profile',[ProfileUserController::class, 'index'])->name('profile.index');
        Route::put('profile/{id}',[ProfileUserController::class, 'update'])->name('profile.update');
    });
//});

app/Models/Order.php
<?php

namespace App\Models;

use App\Traits\HasChannel;
use App\Traits\HasProduct;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Order extends Model
{
    use HasFactory, HasProduct, HasChannel;

    protected $fillable = ['name','sku','status', 'phone', 'address', 'note', 'tax', 'sub_total', 'total'];

    public function detail()
    {
        return $this->hasMany(OrderDetail::class, 'order_id');
    }
}

app/Http/Controllers/API/OrderController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Resources\API\OrderDetailResource;
use App\Http\Resources\API\OrderResource;
use App\Models\Order;
use App\Models\OrderDetail;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        // Insert to Order
        $order = Order::create($data['order']);
        //Insert OrderDetail
        $detail = $data['orderDetail'];
        foreach ($detail as &$value) {
            $value['order_id'] = $order->id;
        }

        OrderDetail::insert($detail);
        
        return new OrderDetailResource($order);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order, int $id)
    {
        $data = Order::with('detail')
        ->find($id);

        return new OrderDetailResource($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends BaseController
{
    public function __construct()
    {
        $this->model = new Order();
        parent::__construct();
    }

    public function store(Request $request)
    {
        return $this->insert_data($request);
    }


    public function update(Request $request, Order $order)
    {
        return $this->insert_data($request, $order);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/backend/layouts/order/_form.blade.php
@if ($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      @if(session()->has('channel'))
      <input type="hidden" name="channels[]" value="{{ Session::get('channel')->id}}" />
      @endif
      <div class="form-group">
        <label for="name">SKU</label>
        {!! Form::text('sku', null, ['class'=>'form-control form-control-sm', 'placeholder' => 'SKU' ]) !!}
      </div>
      <div class="form-group">
        <label for="status">Status</label>
        @php
          $status = [0 => 'pending', 1 => 'processing', 2 => 'done', 3 => 'cancled'];
        @endphp
        {!! Form::select('status', $status, $data->status, ['class' => 'form-control form-control-sm']) !!}
      </div>
      <div class="form-group">
        <label for="tax">Tax %</label>
        @php
          $tax = [0 => '0%', 3 => '3%', 10 => '10%'];
        @endphp
        {!! Form::select('tax', $tax, $data->tax, ['class' => 'form-control form-control-sm']) !!}
      </div>
      <div class="form-group">
        <label for="note">Note</label>
        {!! Form::textarea('note', null, ['class'=>'tiny-desc form-control form-control-sm']) !!}
      </div>
    </div>
    <div class="col-md-8">
      <select class="order-products select2" multiple="multiple" name="products[]" data-dropdown-css-class="select2-purple" style="width: 100%;">
        @foreach($products as $product)
          <option value="{{ $product->id }}">{{ $product->translated->name }}</option>
        @endforeach
        
      </select>
        
    </div>
  </div>
</div>

resources/views/backend/layouts/order/create.blade.php
@extends('backend.main')
@section('title', 'Orders')
@section('content')
{!! Form::open(['method' => 'post', 'route' => 'order.store']) !!}
<div class="card">
	<div class="card-header border-0">
		<h3 class="card-title">Create Order</h3>
		<div class="card-tools">
			@include('backend.partials.form-button',['target' => route('order.index')])
		</div>
	</div>
	<div class="card-body">
		@csrf
		@include('backend.layouts.order._form')
	</div>
</div>
{!! Form::close() !!}
@endsection

resources/views/backend/layouts/order/edit.blade.php
@extends('backend.main')
@section('title', 'Orders')
@section('content')
{!! Form::model($data,['method' => 'put', 'route' => ['order.update', $data->id]]) !!}
<div class="card">
    <div class="card-header border-0">
        <h3 class="card-title">Order edit</h3>
        <div class="card-tools">
            @include('backend.partials.form-button',['target' => route('order.index')])
        </div>
    </div>
    <div class="card-body">
        @csrf
        @include('backend.layouts.order._form')
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/backend/layouts/order/index.blade.php
@extends('backend.main')
@section('title', 'Orders')
@section('content')
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">orders</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>SKU</th>
                        <th>Tax %</th>
                        <th>Total</th>
                        <th>Sub total</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $order)
                        <tr>
                            <td>{{ $order->id }}</td>
                            <td>{{ $order->sku }}</td>
                            <td>{{ $order->tax }}</td>
                            <td>{{ $order->total }}</td>
                            <td>{{ $order->sub_total }}</td>
                            <td>{{ $order->status }}</td>
                            <td>
                                @include('backend.partials.list-action-button', [
                                    'href' => route('order.edit', $order->id),
                                    'deleteRoute' => route('order.destroy',$order->id)
                                ])
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="7">{{ $data->links() }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection