routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\InfoWebController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Livewire\Admin\Article\ArticleCreate;
use App\Http\Livewire\Admin\Article\ArticleEdit;
use App\Http\Livewire\Admin\Article\ArticleIndex;
use App\Http\Livewire\Admin\Category\CategoryCreate;
use App\Http\Livewire\Admin\Category\CategoryEdit;
use App\Http\Livewire\Admin\Category\CategoryIndex;
use App\Http\Livewire\Admin\Code\CodeIndex;
use App\Http\Livewire\Admin\File\FileIndex;
use App\Http\Livewire\Admin\Product\ProductCreate;
use App\Http\Livewire\Admin\Product\ProductEdit;
use App\Http\Livewire\Admin\Product\ProductIndex;
use App\Http\Livewire\Admin\Slide\LogoIndex;
use App\Http\Livewire\Admin\Slide\SlideCreate;
use App\Http\Livewire\Admin\Slide\SlideEdit;
use App\Http\Livewire\Admin\Slide\SlideIndex;
use App\Http\Livewire\Admin\WebInfo\WebInfoIndex;
use App\Models\WebInformation;
use Illuminate\Support\Facades\Route;



// Main route admin
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified', 'locale', 'is_admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [BaseController::class, 'dashboard'])->name('admin.dashboard');
        // Route::resource('/product', ProductController::class);
        // Route::resource('/article', ArticleController::class);
        // Route::resource('/category',CategoryController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/channel', ChannelController::class);
        Route::resource('/partner', PartnerController::class);
        Route::resource('/order', OrderController::class);
        Route::resource('/infoweb', InfoWebController::class);
        Route::get('/info', [InformationController::class, 'show'])->name('info.show');
        Route::put('/info', [InformationController::class, 'save'])->name('info.save');
        Route::put('/update-password', [UserController::class, 'updatePassword'])->name('users.update-password');
        Route::get('change-language/{lang}', [BaseController::class, 'changeLanguage'])->name('admin.changeLanguage');
        Route::get('channel/{channelSlug}', [BaseController::class, 'channel'])->name('admin.channel');
        Route::get('posts/api', [PostController::class, 'getPosts']);

        //logo
        Route::get('web-info', WebInfoIndex::class)->name('webinfo.index');
        // Route::post('/',[LogoController::class,'changeLogoImage'])->name('change.logo');
        //File
        Route::get('file', FileIndex::class)->name('file.index');
        // Slide
        Route::get('slide',SlideIndex::class)->name('slide.index');
        Route::get('slide/create',SlideCreate::class)->name('slide.create');
        Route::get('slide/edit/{slide}',SlideEdit::class)->name('slide.edit');
        // Code 
        // Route::get('code',CodeIndex::class)->name('code.index');
        //Category 
        Route::get('category', CategoryIndex::class)->name('category.index');
        Route::get('category/create', CategoryCreate::class)->name('category.create');
        Route::get('category/edit/{category}', CategoryEdit::class)->name('category.edit');
        // Product
        Route::get('product', ProductIndex::class)->name('product.index');
        Route::get('product/create', ProductCreate::class)->name('product.create');
        Route::get('product/edit/{product}', ProductEdit::class)->name('product.edit');
        // Article
        Route::get('article', ArticleIndex::class)->name('article.index');
        Route::get('article/create', ArticleCreate::class)->name('article.create');
        Route::get('article/edit/{article}', ArticleEdit::class)->name('article.edit');
    });
});

//Jetstream livewire
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

routes/web.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.layouts.index');
// });

// Route::middleware(['locale'])->group(function(){
    Route::prefix('/')->group(function(){
        Route::get('',[HomeController::class, 'index'])->name('index');
        Route::get('detail/{slug}',[HomeController::class, 'productDetail'])->name('product.detail');
        Route::get('cate/{slug}',[HomeController::class, 'category'])->name('category.product.list');
        Route::get('article',[HomeController::class,'article']);
        Route::get('article/{slug}',[HomeController::class, 'articleDetail'])->name('article.detail');
        Route::get('contact',[HomeController::class, 'contact'])->name('contact');
        Route::get('storeContact',[HomeController::class,'storeContact'])->name('storeContact');
        Route::post('search',[HomeController::class, 'search'])->name('search');
        Route::get('profile',[ProfileUserController::class, 'index'])->name('profile.index');
        Route::put('profile/{id}',[ProfileUserController::class, 'update'])->name('profile.update');
    });
//});

app/Models/Channel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    protected $fillable = ['name','slug','is_active','is_default'];
}

app/Http/Controllers/Admin/ChannelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Channel;
use Illuminate\Http\Request;

class ChannelController extends BaseController
{
    public function __construct()
    {
        $this->model = new Channel();
        parent::__construct();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except('_token','_method');
        $data['slug'] = createSlug($data['name']);
        $channels = Channel::create($data);

        return redirect()->route('channels.edit',$channels->id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Channel  $channel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Channel $channel)
    {
        $data = $request->except('_token','_method');
        $data['slug'] = createSlug($data['name']);
        if ($data['is_default'] == 1) {
            Channel::whereNotIn('id',[$channel->id])->update(['is_default' => false]);
        }

        Channel::find($channel->id)->update($data);

        return redirect()->back();
    }


}

resources/views/backend/layouts/channel/_form.blade.php
@if ($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label for="name">{{ trans('origin.name')}}</label>
        {!! Form::text('name', null, ['class'=>'form-control form-control-sm', 'placeholder' => trans('product.placeholder_name') ]) !!}
      </div>

      <div class="form-group">
        <div class="custom-control custom-switch">
          {!! Form::hidden('is_active', 0, []) !!}
          {!! Form::checkbox('is_active', 1, $data->is_active, ['class' => 'custom-control-input', 'id' => 'is_active']) !!}
          <label class="custom-control-label" for="is_active">{{ trans('origin.is_active')}}</label>
        </div>
      </div>

      <div class="form-group">
        <div class="custom-control custom-switch">
          {!! Form::hidden('is_default', 0, []) !!}
          {!! Form::checkbox('is_default', 1, $data->is_default, ['class' => 'custom-control-input', 'id' => 'is_default']) !!}
          <label class="custom-control-label" for="is_default">{{ trans('origin.is_default')}}</label>
        </div>
      </div>

      
    </div>
  </div>
</div>

resources/views/backend/layouts/channel/create.blade.php
@extends('backend.main')
@section('title', trans('product.create_product'))
@section('content')
{!! Form::open(['method' => 'post', 'route' => 'channel.store']) !!}
<div class="card">
	<div class="card-header border-0">
		<h3 class="card-title">{{ trans('origin.create') }}</h3>
		<div class="card-tools">
			@include('backend.partials.form-button',['target' => route('channel.index')])
		</div>
	</div>
	<div class="card-body">
		@csrf
		@include('backend.layouts.channel._form')
	</div>
</div>
{!! Form::close() !!}
@endsection

resources/views/backend/layouts/channel/edit.blade.php
@extends('backend.main')
@section('title', trans('product.edit_product'))
@section('content')
{!! Form::model($data,['method' => 'put', 'route' => ['channel.update', $data->id]]) !!}
<div class="card">
    <div class="card-header border-0">
        <h3 class="card-title">{{ trans('origin.edit')}}</h3>
        <div class="card-tools">
            @include('backend.partials.form-button',['target' => route('channel.index')])
        </div>
    </div>
    <div class="card-body">
        @csrf
        @include('backend.layouts.channel._form')
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/backend/layouts/channel/index.blade.php
@extends('backend.main')
@section('title', trans('product.product'))
@section('content')
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">Channels</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ trans('channel.name')}}</th>
                        <th>{{ trans('channel.slug')}}</th>
                        <th>{{ trans('channel.is_active')}}</th>
                        <th>{{ trans('channel.is_default')}}</th>
                        <th>{{ trans('channel.more')}}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($channels as $channel)
                        <tr>
                            <td>{{ $channel->id }}</td>
                            <td>{{ $channel->name }}</td>
                            <td>{{ $channel->slug }}</td>
                            <td>{{ $channel->is_active }}</td>
                            <td>{{ $channel->is_default }}</td>
                            <td>
                                @include('backend.partials.list-action-button', [
                                    'href' => route('channel.edit', $channel->id),
                                    'deleteRoute' => route('channel.destroy',$channel->id)
                                ])
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection