routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\InfoWebController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Livewire\Admin\Article\ArticleCreate;
use App\Http\Livewire\Admin\Article\ArticleEdit;
use App\Http\Livewire\Admin\Article\ArticleIndex;
use App\Http\Livewire\Admin\Category\CategoryCreate;
use App\Http\Livewire\Admin\Category\CategoryEdit;
use App\Http\Livewire\Admin\Category\CategoryIndex;
use App\Http\Livewire\Admin\Code\CodeIndex;
use App\Http\Livewire\Admin\File\FileIndex;
use App\Http\Livewire\Admin\Product\ProductCreate;
use App\Http\Livewire\Admin\Product\ProductEdit;
use App\Http\Livewire\Admin\Product\ProductIndex;
use App\Http\Livewire\Admin\Slide\LogoIndex;
use App\Http\Livewire\Admin\Slide\SlideCreate;
use App\Http\Livewire\Admin\Slide\SlideEdit;
use App\Http\Livewire\Admin\Slide\SlideIndex;
use App\Http\Livewire\Admin\WebInfo\WebInfoIndex;
use App\Models\WebInformation;
use Illuminate\Support\Facades\Route;



// Main route admin
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified', 'locale', 'is_admin'])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [BaseController::class, 'dashboard'])->name('admin.dashboard');
        // Route::resource('/product', ProductController::class);
        // Route::resource('/article', ArticleController::class);
        // Route::resource('/category',CategoryController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/channel', ChannelController::class);
        Route::resource('/partner', PartnerController::class);
        Route::resource('/order', OrderController::class);
        Route::resource('/infoweb', InfoWebController::class);
        Route::get('/info', [InformationController::class, 'show'])->name('info.show');
        Route::put('/info', [InformationController::class, 'save'])->name('info.save');
        Route::put('/update-password', [UserController::class, 'updatePassword'])->name('users.update-password');
        Route::get('change-language/{lang}', [BaseController::class, 'changeLanguage'])->name('admin.changeLanguage');
        Route::get('channel/{channelSlug}', [BaseController::class, 'channel'])->name('admin.channel');
        Route::get('posts/api', [PostController::class, 'getPosts']);

        //logo
        Route::get('web-info', WebInfoIndex::class)->name('webinfo.index');
        // Route::post('/',[LogoController::class,'changeLogoImage'])->name('change.logo');
        //File
        Route::get('file', FileIndex::class)->name('file.index');
        // Slide
        Route::get('slide',SlideIndex::class)->name('slide.index');
        Route::get('slide/create',SlideCreate::class)->name('slide.create');
        Route::get('slide/edit/{slide}',SlideEdit::class)->name('slide.edit');
        // Code 
        // Route::get('code',CodeIndex::class)->name('code.index');
        //Category 
        Route::get('category', CategoryIndex::class)->name('category.index');
        Route::get('category/create', CategoryCreate::class)->name('category.create');
        Route::get('category/edit/{category}', CategoryEdit::class)->name('category.edit');
        // Product
        Route::get('product', ProductIndex::class)->name('product.index');
        Route::get('product/create', ProductCreate::class)->name('product.create');
        Route::get('product/edit/{product}', ProductEdit::class)->name('product.edit');
        // Article
        Route::get('article', ArticleIndex::class)->name('article.index');
        Route::get('article/create', ArticleCreate::class)->name('article.create');
        Route::get('article/edit/{article}', ArticleEdit::class)->name('article.edit');
    });
});

//Jetstream livewire
Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

routes/web.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\InformationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ChannelController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileUserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.layouts.index');
// });

// Route::middleware(['locale'])->group(function(){
    Route::prefix('/')->group(function(){
        Route::get('',[HomeController::class, 'index'])->name('index');
        Route::get('detail/{slug}',[HomeController::class, 'productDetail'])->name('product.detail');
        Route::get('cate/{slug}',[HomeController::class, 'category'])->name('category.product.list');
        Route::get('article',[HomeController::class,'article']);
        Route::get('article/{slug}',[HomeController::class, 'articleDetail'])->name('article.detail');
        Route::get('contact',[HomeController::class, 'contact'])->name('contact');
        Route::get('storeContact',[HomeController::class,'storeContact'])->name('storeContact');
        Route::post('search',[HomeController::class, 'search'])->name('search');
        Route::get('profile',[ProfileUserController::class, 'index'])->name('profile.index');
        Route::put('profile/{id}',[ProfileUserController::class, 'update'])->name('profile.update');
    });
//});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HasChannel;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use HasChannel;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'address', 'note', 'IDNo', 'profile_photo_path', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserCreateRequest;
use App\Http\Requests\Admin\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Laravel\Fortify\Contracts\UpdatesUserPasswords;

class UserController extends BaseController
{
    public function __construct()
    {
        $this->model = new User();
        parent::__construct();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {
        if($request->get('password') != $request->get('confirm_password')){
            // confirm password not match
            return redirect()->back()->with("error","Password and confirm password does not match.");
        }

        if($request->get('password') == ''){
            // password empty
            return redirect()->back()->with("error","Password can not empty.");
        }

        $data = $request->all();
        $data['password'] = Hash::make($data['password']);

        $new = User::create($data);

        return redirect()->route('users.edit',$new->id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $data = $request->all();
        $user->update($data);

        return redirect()->route('users.edit',$user->id);
    }

    /**
     * Validate and update the user's password.
     *
     * @param  mixed  $user
     * @param  array  $input
     * @return void
     */
    public function updatePassword(Request $request)
    {

        if (!(Hash::check($request->get('current-password'), Auth::user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error","Your current password does not matches with the password.");
        }

        if(strcmp($request->get('current-password'), $request->get('new-password')) == 0){
            // Current password and new password same
            return redirect()->back()->with("error","New Password cannot be same as your current password.");
        }

        $validatedData = $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:8|confirmed',
        ]);

        //Change Password
        $user = Auth::user();
        $password = Hash::make($request->get('new-password'));
        User::where('id',$user->id)->update(['password' => $password]);

        return redirect()->back()->with("success","Password successfully changed!");
    }
}

resources/views/backend/layouts/user/_form.blade.php
@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif
@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
@if ($errors)
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger">{{ $error }}</div>
    @endforeach
@endif
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      @if(session()->has('channel'))
        <input type="hidden" name="channels[]" value="{{ Session::get('channel')->id}}" />
      @endif
      <div class="form-group">
        <label for="name">{{ trans('user.user_name')}} *</label>
        {!! Form::text('name', null, ['class'=>'form-control form-control-sm', 'required']) !!}
      </div>

      <div class="form-group">
        <label for="email">{{ trans('origin.email')}} *</label>
        {!! Form::text('email', null, ['class'=>'form-control form-control-sm', 'required']) !!}
      </div>

      <div class="form-group">
        <label for="phone">{{ trans('origin.phone')}} *</label>
        {!! Form::text('phone', null, ['class'=>'form-control form-control-sm', 'required']) !!}
      </div>

      <div class="form-group">
        <label for="address">{{ trans('origin.address')}}</label>
        {!! Form::text('address', null, ['class'=>'form-control form-control-sm']) !!}
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <div class="custom-control custom-switch">
          {!! Form::hidden('is_active', 0, []) !!}
          {!! Form::checkbox('is_active', 1, $data->is_active, ['class' => 'custom-control-input', 'id' => 'is_active']) !!}
          <label class="custom-control-label" for="is_active">{{ trans('origin.is_active')}}</label>
        </div>
      </div>

      <div class="form-group">
        <div class="custom-control custom-switch">
          {!! Form::hidden('is_admin', 0, []) !!}
          {!! Form::checkbox('is_admin', 1, $data->is_admin, ['class' => 'custom-control-input', 'id' => 'is_admin']) !!}
          <label class="custom-control-label" for="is_admin">{{ trans('user.is_admin')}}</label>
        </div>
      </div>

      @if(request()->routeIS('users.create'))
        <div class="form-group">
          <label for="password">{{ trans('user.password')}} *</label>
          {!! Form::password('password', ['class'=>'form-control form-control-sm', 'required']) !!}
        </div>
        <div class="form-group">
          <label for="confirm_password">{{ trans('user.confirm_password')}} *</label>
          {!! Form::password('confirm_password', ['class'=>'form-control form-control-sm', 'required']) !!}
        </div>
      @else
        <!-- change password form -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#change-password">
          {{ trans('user.change_password')}}
        </button>
      @endif
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label for="profile_photo_path">{{ trans('user.profile_photo_path')}}</label>
        {!! Form::hidden('profile_photo_path', null,['class' => 'form-control form-control-sm', 'id' => 'img']) !!}
        <a data-fancybox data-type="iframe" data-src="{{ url('plugins/filemanager/dialog.php?type=1&field_id=img') }}"
          href="javascript:;">
          (click here to browse...)
        </a>
        <div class="text-center">
          <img id="view-img" src="{{ isset($data->profile_photo_path) ? $data->profile_photo_path : null}}">
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <label for="note">{{ trans('origin.note')}}</label>
        {!! Form::textarea('note', null, ['class'=>'form-control form-control-sm tiny-desc' , 'id' => 'desc']) !!}
      </div>
    </div>
  </div>
</div>

resources/views/backend/layouts/user/create.blade.php
@extends('backend.main')
@section('title', trans('origin.create'))
@section('content')
{!! Form::open(['method' => 'post', 'route' => 'user.store']) !!}
<div class="card">
	<div class="card-header border-0">
		<h3 class="card-title">{{ trans('origin.create') }}</h3>
		<div class="card-tools">
			@include('backend.partials.form-button',['target' => route('user.index')])
		</div>
	</div>
	<div class="card-body">
		@csrf
		@include('backend.layouts.user._form')
	</div>
</div>
{!! Form::close() !!}
@endsection

resources/views/backend/layouts/user/edit.blade.php
@extends('backend.main')
@section('title', trans('origin.edit'))
@section('content')
    {!! Form::model($data, ['method' => 'put', 'route' => ['user.update', $data->id]]) !!}
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">{{ trans('origin.edit') }}</h3>
            <div class="card-tools">
                @include('backend.partials.form-button',['target' => route('user.index')])
            </div>
        </div>
        <div class="card-body">
            @csrf
            {!! Form::hidden('id', null, ['class'=>'form-control form-control-sm', 'required']) !!}
            @include('backend.layouts.user._form')
        </div>
    </div>
    {!! Form::close() !!}

    <!-- Change password -->
    <div class="modal fade" id="change-password" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ trans('origin.change_password') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="panel-body">
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if ($errors)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">{{ $error }}</div>
                            @endforeach
                        @endif
                        <form class="form-horizontal" method="POST" action="{{ route('users.update-password') }}">
                            {{ csrf_field() }}
                            @method('PUT')
                            <div class="form-group{{ $errors->has('current-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">{{ trans('user.current_password') }} *</label>

                                <div class="col-md-6">
                                    <input id="current-password" type="password" class="form-control"
                                        name="current-password" required>

                                    @if ($errors->has('current-password'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('current-password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('new-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">{{ trans('user.new_password') }} *</label>

                                <div class="col-md-6">
                                    <input id="new-password" type="password" class="form-control" name="new-password"
                                        required>

                                    @if ($errors->has('new-password'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('new-password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="new-password-confirm" class="col-md-4 control-label">{{ trans('user.confirm_new_password') }} *</label>

                                <div class="col-md-6">
                                    <input id="new-password-confirm" type="password" class="form-control"
                                        name="new-password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                      {{ trans('user.change_password') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/layouts/user/index.blade.php
@extends('backend.main')
@section('title', trans('user.user'))
@section('content')
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">{{ trans('user.user') }}</h3>
            <div class="card-tools">
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                </a>
                <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-bars"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ trans('user.user_name')}}</th>
                        <th>{{ trans('origin.email')}}</th>
                        <th>{{ trans('user.phone')}}</th>
                        <th>{{ trans('user.is_admin')}}</th>
                        <th>{{ trans('origin.actions')}}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->phone }}</td>
                            <td>{{ $user->is_admin }}</td>
                            <td>
                                @include('backend.partials.list-action-button', [
                                    'href' => route('user.edit', $user->id),
                                    'deleteRoute' => route('user.destroy',$user->id)
                                ])
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="6">{{ $data->links() }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection